disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - weak_delegate
 - explicit_enum_raw_value
 - empty_enum_arguments
 - file_length
 - function_body_length
 
identifier_name:  
  min_length:
    warning: 2
    
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  
nesting:
  type_level: 3


